### Retorna todos os defeitos.
GET http://localhost:8080/defeitos
Accept: application/json

### Retorna o defeito com id 'x'.
GET http://localhost:8080/defeitos/1
Accept: application/json

### Persiste o novo defeito.
POST http://localhost:8080/defeitos
Content-Type: application/json

{
  "quantidade": 1,
  "data": "01/01/2018",
  "pecaFeira": {
    "id": 1
  }
}

### Apaga o defeito com id 'x'.
DELETE http://localhost:8080/defeitos/1

###