### Retorna todos as vendas.
GET http://localhost:8080/vendas
Accept: application/json

### Retorna a venda com id 'x'.
GET http://localhost:8080/vendas/1
Accept: application/json

### Retorna o faturamento do período 'dd/MM/aaaa' à 'dd/MM/aaaa'.
GET http://localhost:8080/vendas?dataInicial=01-01-2018&dataFinal=31-12-2018
Accept: application/json

### Persiste a nova venda.
POST http://localhost:8080/vendas
Content-Type: application/json

{
  "preco": 200.00,
  "quantidade": 1,
  "data": "01/01/2018",
  "pecaFeira": {
    "id": 1
  }
}

### Apagar a venda com id 'x'.
DELETE http://localhost:8080/vendas/1

###

PUT http://localhost:8080/vendas/1/estornar/1

###